# Generated by Django 2.0.5 on 2018-07-01 13:48

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180701_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=mptt.fields.TreeForeignKey(default='other', on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.Category'),
        ),
    ]
