# Generated by Django 2.0.5 on 2018-07-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180701_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='modified_time',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
